name: Release Please

on:
  workflow_call:
    secrets:
      GRAPH_FEDERATOR:
        required: true

jobs:
  release_please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1.11.3
        with:
          app-id: 1215648
          private-key: ${{ secrets.GRAPH_FEDERATOR }}
          repositories: graph-federation

      - name: Bootstrap release-please
        run: |
          npx release-please bootstrap \
            --repo-url=${{ github.repository }} \
            --token=${{ steps.app-token.outputs.token }} \
            --default-branch=dev

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4.1.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          fork: false
